name: Tests

on:
  pull_request:
    branches:
      - 'release/**'
      - 'develop'
      - 'release-app_**'
      - 'master'
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DVELOPMENT_ANDROID }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Check pwd
        run: |
          pwd
      - name: Check ls
        run: |
          ls